### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by OmgImAlexis** [hediet/easy-attach#3]
This is what was thrown as I didn't have `xsel` installed. It'd be nicer to catch the error and print something simpler or maybe even just skip the clipboard copy if it's not installed.

```
Easy Attach Version 0.15.3.

Use this code to trigger a breakpoint:
require("/usr/local/share/.config/yarn/global/node_modules/easy-attach/")();
(Pasted into your clipboard)

/usr/local/share/.config/yarn/global/node_modules/clipboardy/lib/linux.js:7
                throw new Error('Couldn\'t find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel');
                ^

Error: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel
    at handler (/usr/local/share/.config/yarn/global/node_modules/clipboardy/lib/linux.js:7:9)
    at Object.copySync (/usr/local/share/.config/yarn/global/node_modules/clipboardy/lib/linux.js:33:5)
    at Object.exports.writeSync.input [as writeSync] (/usr/local/share/.config/yarn/global/node_modules/clipboardy/index.js:38:13)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/easy-attach/dist/cli.entry.js:16:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
```

**Comment by hediet** [comment]
The error is now:

![image](https://user-images.githubusercontent.com/2931520/54817404-22da1100-4c97-11e9-86f8-81327b69245f.png)
